### ISSUE TITLE
Implementar delquote

### ISSUE THREAD

**Issue by javipolo** [pandacrew/diosteama#29]
Habria que implementar el comando delquote que marque un quote como borrado y este no salga más al buscar y demás

Imagino que para ello lo suyo seria añadir un campo más que sea "deleted" o algo asi

Como bonus estaria bien poder revertir esto, algo asi como un /undelquote para poner el quote como deleted=false

Quizas tambien estaria bien que hubiera un comando /purge o similar que SI que borre de la DB

Asi a bote pronto se me ocurre que a nivel de permisos podria ser:
delquote -> todo el mundo
undelquote, purge -> solo admins y owners del canal

**Comment by itorres** [comment]
Fixed by #38
